server:
  port: 8080

redis:
  address:
    master: redis://127.0.0.1:6379
    slave: redis://172.16.9.113:6379
    cluster: redis://127.0.0.1:7001,redis://127.0.0.1:7002,redis://127.0.0.1:7003,redis://127.0.0.1:7004,redis://127.0.0.1:7005,redis://127.0.0.1:7006
  connectionMode: 3


spring:
    datasource:
        name: wcj
        url: jdbc:mysql://127.0.0.1:3306/wcj?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    redis:
#      cluster:
#        nodes:
#        - 127.0.0.1:7000
#        - 127.0.0.1:7001
#        - 127.0.0.1:7002
#        - 127.0.0.1:7003
#        - 127.0.0.1:7004
#        - 127.0.0.1:7005
#      pool:
#        max-active: 10
#        maxIdle: 0
    thymeleaf:
      encoding: UTF-8
      checkTemplate: true
      checkTemplateLocation: true
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      contentType: text/html
      cache: false

mybatis:
    config-location: classpath:mybatis-config.xml
logging:
  level: debug


